- name: Install Docker
  shell: |
    curl -fsSL https://get.docker.com -o get-docker.sh
    sh get-docker.sh
  args:
    creates: /usr/bin/docker

- name: Add user to docker group
  user:
    name: "{{ hostvars['localhost'].deploy_user }}"
    groups: docker
    append: yes

- name: Install Docker Compose plugin
  apt:
    name: docker-compose-plugin
    state: present

