- name: Prompt for SSH user and pihole password
  hosts: localhost
  gather_facts: false
  connection: local
  vars_prompt:
    - name: deploy_user
      prompt: "Enter the SSH user for target hosts"
      private: no
    - name: pihole_password
      prompt: "Enter the admin password for pihole"
      private: yes

- name: Bootstrap base packages as root
  hosts: all
  remote_user: "{{ hostvars['localhost'].deploy_user }}"
  become: true
  become_method: su
  roles:
    - base
    - users

- name: Install Docker on all hosts
  hosts: all
  remote_user: "{{ hostvars['localhost'].deploy_user }}"
  become: true
  become_method: sudo
  roles:
    - docker_apps

- name: Network host setup
  hosts: network
  remote_user: "{{ hostvars['localhost'].deploy_user }}"
  become: true
  become_method: sudo
  vars:
    pihole_password: "{{ hostvars['localhost'].pihole_password }}"
  roles:
    - network

- name: Media host setup
  hosts: media
  remote_user: "{{ hostvars['localhost'].deploy_user }}"
  become: true
  become_method: sudo
  roles:
    - media
